import sqlite3
from datetime import datetime

import psycopg

from app.database.connection import get_connection, DEFAULT_USER_ID
from app.expense import Expense


def _is_postgres(connection):
    """
    Check whether the active database connection is PostgreSQL.
    """
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    """
    Return the correct SQL parameter placeholder.
    """
    return "%s" if _is_postgres(connection) else "?"


def initialize_database():
    connection = get_connection()

    try:
        if _is_postgres(connection):
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS expenses (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    description TEXT NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    category TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    user_id UUID NOT NULL
                )
                """
            )

        else:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS expenses (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    description TEXT NOT NULL,
                    amount REAL NOT NULL,
                    category TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    user_id TEXT
                )
                """
            )

            # Existing local SQLite databases may already have
            # the expenses table without user_id.
            columns = connection.execute(
                "PRAGMA table_info(expenses)"
            ).fetchall()

            column_names = [column["name"] for column in columns]

            if "user_id" not in column_names:
                connection.execute(
                    "ALTER TABLE expenses ADD COLUMN user_id TEXT"
                )

        if _is_postgres(connection):
            connection.execute(
                "CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id)"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS idx_expenses_user_created ON expenses(user_id, created_at)"
            )
        else:
            connection.execute(
                "CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id)"
            )

        connection.commit()

    except (sqlite3.Error, psycopg.Error):
        connection.rollback()
        raise

    finally:
        connection.close()


class ExpenseRepository:

    def initialize_table(self):
        initialize_database()

    def add(self, expense, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO expenses (
                        description,
                        amount,
                        category,
                        created_at,
                        user_id
                    )
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        expense.description,
                        expense.amount,
                        expense.category,
                        expense.created_at,
                        user_id,
                    )
                )

                expense.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO expenses (
                        description,
                        amount,
                        category,
                        created_at,
                        user_id
                    )
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        expense.description,
                        expense.amount,
                        expense.category,
                        expense.created_at.isoformat(),
                        user_id,
                    )
                )

                expense.id = cursor.lastrowid

            connection.commit()

            return expense

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_all(self, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM expenses
                WHERE user_id = {placeholder}
                ORDER BY id
                """,
                (user_id,)
            ).fetchall()

            return self._convert_rows_to_expenses(rows)

        finally:
            connection.close()

    def get_by_id(self, expense_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM expenses
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (expense_id, user_id)
            ).fetchone()

            if not row:
                return None

            return self._convert_rows_to_expenses([row])[0]

        finally:
            connection.close()

    def update(self, expense, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE expenses
                SET description = {placeholder},
                    amount = {placeholder},
                    category = {placeholder}
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    expense.description,
                    expense.amount,
                    expense.category,
                    expense.id,
                    user_id,
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, expense_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM expenses
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    expense_id,
                    user_id,
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_date(self, date, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            if _is_postgres(connection):
                query = f"""
                    SELECT
                        id,
                        description,
                        amount,
                        category,
                        created_at
                    FROM expenses
                    WHERE created_at::date = {placeholder}
                      AND user_id = {placeholder}
                    ORDER BY id
                """
            else:
                query = f"""
                    SELECT
                        id,
                        description,
                        amount,
                        category,
                        created_at
                    FROM expenses
                    WHERE DATE(created_at) = {placeholder}
                      AND user_id = {placeholder}
                    ORDER BY id
                """

            rows = connection.execute(
                query,
                (
                    date,
                    user_id,
                )
            ).fetchall()

            return self._convert_rows_to_expenses(rows)

        finally:
            connection.close()

    def search_by_description(self, keyword, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            if _is_postgres(connection):
                query = f"""
                    SELECT
                        id,
                        description,
                        amount,
                        category,
                        created_at
                    FROM expenses
                    WHERE description ILIKE {placeholder}
                      AND user_id = {placeholder}
                    ORDER BY created_at DESC
                """
            else:
                query = f"""
                    SELECT
                        id,
                        description,
                        amount,
                        category,
                        created_at
                    FROM expenses
                    WHERE description LIKE {placeholder}
                      AND user_id = {placeholder}
                    ORDER BY created_at DESC
                """

            rows = connection.execute(
                query,
                (
                    f"%{keyword}%",
                    user_id,
                )
            ).fetchall()

            return self._convert_rows_to_expenses(rows)

        finally:
            connection.close()

    def filter_by_category(self, category, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM expenses
                WHERE LOWER(category) = LOWER({placeholder})
                  AND user_id = {placeholder}
                ORDER BY created_at DESC
                """,
                (
                    category,
                    user_id,
                )
            ).fetchall()

            return self._convert_rows_to_expenses(rows)

        finally:
            connection.close()

    def filter_by_amount_range(
        self,
        minimum,
        maximum,
        user_id=DEFAULT_USER_ID
    ):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM expenses
                WHERE amount BETWEEN {placeholder} AND {placeholder}
                  AND user_id = {placeholder}
                ORDER BY amount ASC
                """,
                (
                    minimum,
                    maximum,
                    user_id,
                )
            ).fetchall()

            return self._convert_rows_to_expenses(rows)

        finally:
            connection.close()

    def _convert_rows_to_expenses(self, rows):
        expenses = []

        for row in rows:
            created_at = row["created_at"]

            if isinstance(created_at, str):
                created_at = datetime.fromisoformat(created_at)

            expense = Expense(
                row["id"],
                row["description"],
                row["amount"],
                row["category"],
                created_at
            )

            expenses.append(expense)

        return expenses