import sqlite3

import psycopg

from app.database.connection import get_connection, DEFAULT_USER_ID
from app.recurring.recurring_expense import RecurringExpense


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class RecurringExpenseRepository:

    def __init__(self):
        self._initialize_table()

    def _initialize_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS recurring_expenses (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        description TEXT NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        category TEXT NOT NULL,
                        frequency TEXT NOT NULL,
                        start_date DATE NOT NULL,
                        end_date DATE,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        user_id UUID NOT NULL
                    )
                    """
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_recurring_user_id ON recurring_expenses(user_id)"
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS recurring_expenses (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        description TEXT NOT NULL,
                        amount REAL NOT NULL,
                        category TEXT NOT NULL,
                        frequency TEXT NOT NULL,
                        start_date TEXT NOT NULL,
                        end_date TEXT,
                        active INTEGER NOT NULL DEFAULT 1,
                        user_id TEXT
                    )
                    """
                )

                # Existing SQLite databases may already have
                # the table without user_id.
                columns = connection.execute(
                    "PRAGMA table_info(recurring_expenses)"
                ).fetchall()

                column_names = [
                    column["name"]
                    for column in columns
                ]

                if "user_id" not in column_names:
                    connection.execute(
                        "ALTER TABLE recurring_expenses ADD COLUMN user_id TEXT"
                    )

                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_recurring_user_id ON recurring_expenses(user_id)"
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, recurring_expense, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO recurring_expenses (
                        description,
                        amount,
                        category,
                        frequency,
                        start_date,
                        end_date,
                        active,
                        user_id
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        recurring_expense.description,
                        recurring_expense.amount,
                        recurring_expense.category,
                        recurring_expense.frequency,
                        recurring_expense.start_date,
                        recurring_expense.end_date,
                        recurring_expense.active,
                        user_id
                    )
                )

                recurring_expense.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO recurring_expenses (
                        description,
                        amount,
                        category,
                        frequency,
                        start_date,
                        end_date,
                        active,
                        user_id
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        recurring_expense.description,
                        recurring_expense.amount,
                        recurring_expense.category,
                        recurring_expense.frequency,
                        recurring_expense.start_date,
                        recurring_expense.end_date,
                        int(recurring_expense.active),
                        user_id
                    )
                )

                recurring_expense.id = cursor.lastrowid

            connection.commit()

            return recurring_expense

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get(self, recurring_expense_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    frequency,
                    start_date,
                    end_date,
                    active
                FROM recurring_expenses
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    recurring_expense_id,
                    user_id
                )
            ).fetchone()

            if row is None:
                return None

            return self._row_to_expense(row)

        finally:
            connection.close()

    def get_all(self, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    frequency,
                    start_date,
                    end_date,
                    active
                FROM recurring_expenses
                WHERE user_id = {placeholder}
                ORDER BY id
                """,
                (user_id,)
            ).fetchall()

            return [
                self._row_to_expense(row)
                for row in rows
            ]

        finally:
            connection.close()

    def update(self, recurring_expense, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            active_value = (
                recurring_expense.active
                if _is_postgres(connection)
                else int(recurring_expense.active)
            )

            cursor = connection.execute(
                f"""
                UPDATE recurring_expenses
                SET
                    description = {placeholder},
                    amount = {placeholder},
                    category = {placeholder},
                    frequency = {placeholder},
                    start_date = {placeholder},
                    end_date = {placeholder},
                    active = {placeholder}
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    recurring_expense.description,
                    recurring_expense.amount,
                    recurring_expense.category,
                    recurring_expense.frequency,
                    recurring_expense.start_date,
                    recurring_expense.end_date,
                    active_value,
                    recurring_expense.id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, recurring_expense_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM recurring_expenses
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    recurring_expense_id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def _row_to_expense(self, row):
        start_date = row["start_date"]
        end_date = row["end_date"]

        # PostgreSQL DATE values are returned as Python date objects.
        # SQLite stores these values as strings.
        if hasattr(start_date, "isoformat"):
            start_date = start_date.isoformat()

        if end_date is not None and hasattr(end_date, "isoformat"):
            end_date = end_date.isoformat()

        return RecurringExpense(
            row["id"],
            row["description"],
            row["amount"],
            row["category"],
            row["frequency"],
            start_date,
            end_date,
            bool(row["active"])
        )