from datetime import datetime
import sqlite3

import psycopg

from app.database.connection import get_connection
from app.budget.budget import Budget


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class BudgetRepository:

    def initialize_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS budgets (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        month TEXT NOT NULL UNIQUE,
                        amount DOUBLE PRECISION NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS budgets (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        month TEXT NOT NULL UNIQUE,
                        amount REAL NOT NULL,
                        created_at TEXT NOT NULL
                    )
                    """
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, budget):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO budgets (
                        month,
                        amount,
                        created_at
                    )
                    VALUES (%s, %s, %s)
                    RETURNING id
                    """,
                    (
                        budget.month,
                        budget.amount,
                        budget.created_at
                    )
                )

                budget.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO budgets (
                        month,
                        amount,
                        created_at
                    )
                    VALUES (?, ?, ?)
                    """,
                    (
                        budget.month,
                        budget.amount,
                        budget.created_at.isoformat()
                    )
                )

                budget.id = cursor.lastrowid

            connection.commit()

            return budget

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_month(self, month):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    month,
                    amount,
                    created_at
                FROM budgets
                WHERE month = {placeholder}
                """,
                (month,)
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_budget(row)

        finally:
            connection.close()

    def get_all(self):
        connection = get_connection()

        try:
            rows = connection.execute(
                """
                SELECT
                    id,
                    month,
                    amount,
                    created_at
                FROM budgets
                ORDER BY month
                """
            ).fetchall()

            return [
                self._convert_row_to_budget(row)
                for row in rows
            ]

        finally:
            connection.close()

    def update(self, budget):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE budgets
                SET month = {placeholder},
                    amount = {placeholder}
                WHERE id = {placeholder}
                """,
                (
                    budget.month,
                    budget.amount,
                    budget.id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, budget_id):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM budgets
                WHERE id = {placeholder}
                """,
                (budget_id,)
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def _convert_row_to_budget(self, row):
        created_at = row["created_at"]

        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)

        return Budget(
            row["id"],
            row["month"],
            row["amount"],
            created_at
        )