from datetime import datetime
import sqlite3

import psycopg

from app.database.connection import get_connection, DEFAULT_USER_ID
from app.budget.budget import Budget


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class BudgetRepository:

    def initialize_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS budgets (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        month TEXT NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        user_id UUID NOT NULL
                    )
                    """
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON budgets(user_id)"
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_budgets_user_month ON budgets(user_id, month)"
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS budgets (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        month TEXT NOT NULL,
                        amount REAL NOT NULL,
                        created_at TEXT NOT NULL,
                        user_id TEXT
                    )
                    """
                )

                columns = connection.execute(
                    "PRAGMA table_info(budgets)"
                ).fetchall()

                column_names = [
                    column["name"]
                    for column in columns
                ]

                if "user_id" not in column_names:
                    connection.execute(
                        "ALTER TABLE budgets ADD COLUMN user_id TEXT"
                    )

                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON budgets(user_id)"
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, budget, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO budgets (
                        month,
                        amount,
                        created_at,
                        user_id
                    )
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        budget.month,
                        budget.amount,
                        budget.created_at,
                        user_id
                    )
                )

                budget.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO budgets (
                        month,
                        amount,
                        created_at,
                        user_id
                    )
                    VALUES (?, ?, ?, ?)
                    """,
                    (
                        budget.month,
                        budget.amount,
                        budget.created_at.isoformat(),
                        user_id
                    )
                )

                budget.id = cursor.lastrowid

            connection.commit()

            return budget

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_month(self, month, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    month,
                    amount,
                    created_at
                FROM budgets
                WHERE month = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    month,
                    user_id
                )
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_budget(row)

        finally:
            connection.close()

    def get_by_id(self, budget_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    month,
                    amount,
                    created_at
                FROM budgets
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    budget_id,
                    user_id
                )
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_budget(row)

        finally:
            connection.close()

    def get_all(self, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    month,
                    amount,
                    created_at
                FROM budgets
                WHERE user_id = {placeholder}
                ORDER BY month
                """,
                (user_id,)
            ).fetchall()

            return [
                self._convert_row_to_budget(row)
                for row in rows
            ]

        finally:
            connection.close()

    def update(self, budget, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE budgets
                SET month = {placeholder},
                    amount = {placeholder}
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    budget.month,
                    budget.amount,
                    budget.id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, budget_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM budgets
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    budget_id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def _convert_row_to_budget(self, row):
        created_at = row["created_at"]

        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)

        return Budget(
            row["id"],
            row["month"],
            row["amount"],
            created_at
        )