import sqlite3
from datetime import datetime

import psycopg

from app.database.connection import get_connection, DEFAULT_USER_ID
from app.income.income import Income


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class IncomeRepository:

    def initialize_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS incomes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        description TEXT NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        category TEXT NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        user_id UUID NOT NULL
                    )
                    """
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_incomes_user_id ON incomes(user_id)"
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS incomes (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        description TEXT NOT NULL,
                        amount REAL NOT NULL,
                        category TEXT NOT NULL,
                        created_at TEXT NOT NULL,
                        user_id TEXT
                    )
                    """
                )

                columns = connection.execute(
                    "PRAGMA table_info(incomes)"
                ).fetchall()

                column_names = [
                    column["name"]
                    for column in columns
                ]

                if "user_id" not in column_names:
                    connection.execute(
                        "ALTER TABLE incomes ADD COLUMN user_id TEXT"
                    )

                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_incomes_user_id ON incomes(user_id)"
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, income, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO incomes (
                        description,
                        amount,
                        category,
                        created_at,
                        user_id
                    )
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        income.description,
                        income.amount,
                        income.category,
                        income.created_at,
                        user_id
                    )
                )

                income.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO incomes (
                        description,
                        amount,
                        category,
                        created_at,
                        user_id
                    )
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        income.description,
                        income.amount,
                        income.category,
                        income.created_at.isoformat(),
                        user_id
                    )
                )

                income.id = cursor.lastrowid

            connection.commit()

            return income

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_id(self, income_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM incomes
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    income_id,
                    user_id
                )
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_income(row)

        finally:
            connection.close()

    def get_all(self, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM incomes
                WHERE user_id = {placeholder}
                ORDER BY id
                """,
                (user_id,)
            ).fetchall()

            return self._convert_rows_to_incomes(rows)

        finally:
            connection.close()

    def update(self, income, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE incomes
                SET description = {placeholder},
                    amount = {placeholder},
                    category = {placeholder}
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    income.description,
                    income.amount,
                    income.category,
                    income.id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, income_id, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM incomes
                WHERE id = {placeholder}
                  AND user_id = {placeholder}
                """,
                (
                    income_id,
                    user_id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def total(self, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT COALESCE(SUM(amount), 0) AS total
                FROM incomes
                WHERE user_id = {placeholder}
                """,
                (user_id,)
            ).fetchone()

            return row["total"]

        finally:
            connection.close()

    def get_by_category(self, category, user_id=DEFAULT_USER_ID):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            rows = connection.execute(
                f"""
                SELECT
                    id,
                    description,
                    amount,
                    category,
                    created_at
                FROM incomes
                WHERE LOWER(category) = LOWER({placeholder})
                  AND user_id = {placeholder}
                """,
                (
                    category,
                    user_id
                )
            ).fetchall()

            return self._convert_rows_to_incomes(rows)

        finally:
            connection.close()

    def _convert_row_to_income(self, row):
        created_at = row["created_at"]

        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)

        return Income(
            row["id"],
            row["description"],
            row["amount"],
            row["category"],
            created_at
        )

    def _convert_rows_to_incomes(self, rows):
        return [
            self._convert_row_to_income(row)
            for row in rows
        ]