import sqlite3
from datetime import datetime

import psycopg

from app.database.connection import get_connection
from app.income.income import Income


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class IncomeRepository:

    def initialize_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS incomes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        description TEXT NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        category TEXT NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS incomes (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        description TEXT NOT NULL,
                        amount REAL NOT NULL,
                        category TEXT NOT NULL,
                        created_at TEXT NOT NULL
                    )
                    """
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, income):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO incomes (
                        description,
                        amount,
                        category,
                        created_at
                    )
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        income.description,
                        income.amount,
                        income.category,
                        income.created_at
                    )
                )

                income.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO incomes (
                        description,
                        amount,
                        category,
                        created_at
                    )
                    VALUES (?, ?, ?, ?)
                    """,
                    (
                        income.description,
                        income.amount,
                        income.category,
                        income.created_at.isoformat()
                    )
                )

                income.id = cursor.lastrowid

            connection.commit()

            return income

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_id(self, income_id):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT id, description, amount, category, created_at
                FROM incomes
                WHERE id = {placeholder}
                """,
                (income_id,)
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_income(row)

        finally:
            connection.close()

    def get_all(self):
        connection = get_connection()

        try:
            rows = connection.execute(
                """
                SELECT id, description, amount, category, created_at
                FROM incomes
                ORDER BY id
                """
            ).fetchall()

            return self._convert_rows_to_incomes(rows)

        finally:
            connection.close()

    def update(self, income):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE incomes
                SET description = {placeholder},
                    amount = {placeholder},
                    category = {placeholder}
                WHERE id = {placeholder}
                """,
                (
                    income.description,
                    income.amount,
                    income.category,
                    income.id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, income_id):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM incomes
                WHERE id = {placeholder}
                """,
                (income_id,)
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def total(self):
        connection = get_connection()

        try:
            row = connection.execute(
                """
                SELECT COALESCE(SUM(amount), 0) AS total
                FROM incomes
                """
            ).fetchone()

            return row["total"]

        finally:
            connection.close()

    def get_by_category(self, category):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            if _is_postgres(connection):
                query = f"""
                    SELECT id, description, amount, category, created_at
                    FROM incomes
                    WHERE LOWER(category) = LOWER({placeholder})
                    ORDER BY created_at DESC
                """
            else:
                query = f"""
                    SELECT id, description, amount, category, created_at
                    FROM incomes
                    WHERE LOWER(category) = LOWER({placeholder})
                    ORDER BY created_at DESC
                """

            rows = connection.execute(
                query,
                (category,)
            ).fetchall()

            return self._convert_rows_to_incomes(rows)

        finally:
            connection.close()

    def _convert_row_to_income(self, row):
        created_at = row["created_at"]

        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)

        return Income(
            row["id"],
            row["description"],
            row["amount"],
            row["category"],
            created_at
        )

    def _convert_rows_to_incomes(self, rows):
        return [
            self._convert_row_to_income(row)
            for row in rows
        ]