import sqlite3

import psycopg

from app.database.connection import get_connection
from app.goals.goal import Goal


def _is_postgres(connection):
    return isinstance(connection, psycopg.Connection)


def _placeholder(connection):
    return "%s" if _is_postgres(connection) else "?"


class GoalRepository:

    def __init__(self):
        self.create_table()

    def create_table(self):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS goals (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        target_amount DOUBLE PRECISION NOT NULL,
                        current_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
                        target_date DATE,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
            else:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS goals (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT NOT NULL,
                        target_amount REAL NOT NULL,
                        current_amount REAL NOT NULL DEFAULT 0,
                        target_date TEXT,
                        created_at TEXT NOT NULL
                    )
                    """
                )

            connection.commit()

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def add(self, goal):
        connection = get_connection()

        try:
            if _is_postgres(connection):
                cursor = connection.execute(
                    """
                    INSERT INTO goals (
                        name,
                        target_amount,
                        current_amount,
                        target_date,
                        created_at
                    )
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        goal.name,
                        goal.target_amount,
                        goal.current_amount,
                        goal.target_date,
                        goal.created_at
                    )
                )

                goal.id = cursor.fetchone()["id"]

            else:
                cursor = connection.execute(
                    """
                    INSERT INTO goals (
                        name,
                        target_amount,
                        current_amount,
                        target_date,
                        created_at
                    )
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        goal.name,
                        goal.target_amount,
                        goal.current_amount,
                        goal.target_date,
                        goal.created_at.isoformat()
                    )
                )

                goal.id = cursor.lastrowid

            connection.commit()

            return goal

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def get_by_id(self, goal_id):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            row = connection.execute(
                f"""
                SELECT
                    id,
                    name,
                    target_amount,
                    current_amount,
                    target_date,
                    created_at
                FROM goals
                WHERE id = {placeholder}
                """,
                (goal_id,)
            ).fetchone()

            if row is None:
                return None

            return self._convert_row_to_goal(row)

        finally:
            connection.close()

    def get_all(self):
        connection = get_connection()

        try:
            rows = connection.execute(
                """
                SELECT
                    id,
                    name,
                    target_amount,
                    current_amount,
                    target_date,
                    created_at
                FROM goals
                ORDER BY id
                """
            ).fetchall()

            return [
                self._convert_row_to_goal(row)
                for row in rows
            ]

        finally:
            connection.close()

    def update(self, goal):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                UPDATE goals
                SET
                    name = {placeholder},
                    target_amount = {placeholder},
                    current_amount = {placeholder},
                    target_date = {placeholder}
                WHERE id = {placeholder}
                """,
                (
                    goal.name,
                    goal.target_amount,
                    goal.current_amount,
                    goal.target_date,
                    goal.id
                )
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def delete(self, goal_id):
        connection = get_connection()

        try:
            placeholder = _placeholder(connection)

            cursor = connection.execute(
                f"""
                DELETE FROM goals
                WHERE id = {placeholder}
                """,
                (goal_id,)
            )

            connection.commit()

            return cursor.rowcount > 0

        except (sqlite3.Error, psycopg.Error):
            connection.rollback()
            raise

        finally:
            connection.close()

    def _convert_row_to_goal(self, row):
        target_date = row["target_date"]

        if hasattr(target_date, "isoformat"):
            target_date = target_date.isoformat()

        return Goal(
            goal_id=row["id"],
            name=row["name"],
            target_amount=row["target_amount"],
            current_amount=row["current_amount"],
            target_date=target_date
        )